version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:1.2.8-3.11-bullseye
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    env_file:
      - ../.env
